module.exports = {
  purge: ['./components/**/*.{js,ts,jsx,tsx}', './pages/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'media', // 'media' or 'class'
  theme: {
    extend: {
      backgroundImage: (theme) => ({
        'card-cover': 'linear-gradient(to bottom left, rgba(26,32,44,0),  rgba(26,32,44,0.9), rgba(26,32,44,1.0))',
      }),
      colors: {
        'accent-1': '#333',
      },
      spacing: {
        half: '50%',
        bkl: '2.6vw',
        bklfixed: '2.8vw',
        bkw: '5.5vw',
        bklw: '8.1vw',
        '2bklw': '16.2vw',
        bk2wl: '13.6vw',
        line: '1px',
        w1: '1vw',
        w2: '2vw',
        w5: '5vw',
        w10: '10vw',
        wsection: '72.9vw',
        h1: '1vh',
        h2: '2vh',
        h5: '5vh',
        h10: '10vh',
        h32: '32vh',
        hcard: '45vh',
        hmain: '35vh',
        hsection: '63vh',
      },
      zIndex: {
        bottom: '-1',
      },
      sizing: {
        half: '50%',
        bkw: '5.5vw',
        bkl: '2.6vw',
        bklw: '8.1vw',
        '2bklw': '16.2vw',
        bk2wl: '13.6vw',
        line: '1px',
        w1: '1vw',
        w2: '2vw',
        w5: '5vw',
        w10: '10vw',
        wsection: '72.9vw',
        h1: '1vh',
        h2: '2vh',
        h5: '5vh',
        h10: '10vh',
        hcard: '45vh',
        hsection: '63vh',
      },
      fontSize: {
        title: '5rem',
        h1: '2.5em',
        h2: '1.5em',
        h3: '1.25em',
        h4: '1.125em',
        content: '1em',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
